---
- hosts: all
  gather_facts: no

  become: true
  become_user: root

  remote_user: ubuntu
  
  tasks:
    - name: Cleanup /var/tmp/mysql-pv
      file: path=/var/tmp/mysql-pv state=absent

    - name: Shutdown
      command: shutdown -h now


