### You need to use Ansible version 2.5 or later
### The target OS is Ubuntu 16.04.
## 2018/10/07
# Ansible Update loop of apt
# Notice for ISSUE kubernetes-cni
---
- hosts: k8s
  gather_facts: no

  become: true
  become_user: root

  remote_user: ubuntu
  
  tasks:
   
    - name: set timezone
      timezone: name=Asia/Tokyo

    - name: install docker
      apt: name=docker.io state=latest update_cache=yes

    - name: install other packages
      apt: name="{{ packages }}" state=latest
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: add an apt key for kubeadm
      apt_key:
        state: present 
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: add repository 
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        filename: /etc/apt/sources.list.d/kubernetes.list
        state: present

# kubernetes-cni 0.6.0 
# https://github.com/kubernetes/kubernetes/issues/69489
# cat /etc/apt/preferences.d/k8s.pref
# Package: kubernetes-cni
# Pin: version 0.6.0-00*
# Pin-Priority: 900

    - name: install kubeadm packages
      apt: name="{{ packages }}" state=latest update_cache=yes
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl
    
    - block: 
        - name: copy shell
          copy: src=./kube_set.sh  dest=/home/ubuntu/kube_set.sh owner=ubuntu group=ubuntu mode=755

        - name: optional install kubens/kubectx
          git: 
            repo: https://github.com/ahmetb/kubectx.git
            dest: /opt/kubectx

        - name: set slink kubens/kubectx
          file:
            src: '/opt/kubectx/{{ item.src }}'
            dest: '/usr/local/bin/{{ item.dest }}'
            state: link
          with_items:
            - { src: 'kubectx', dest: 'kubectx' }
            - { src: 'kubens', dest: 'kubens' }

        - name: update .bashrc
          blockinfile:
            path: /home/ubuntu/.bashrc
            marker_begin: "BEGIN Auto Completion for k8s by Ansible"
            marker_end: "END Auto Completion for k8s by Ansible"
            block: |
              source <(kubectl completion bash)
              source /opt/kubectx/completion/kubens.bash
              source /opt/kubectx/completion/kubectx.bash
      when: inventory_hostname == '192.168.0.78'


