### You need to use Ansible version 2.8 or later
### The target OS is Ubuntu 18.04
## 2019/08/17
---
- hosts: kind-host
  gather_facts: no

  become: true
  become_user: root

  remote_user: ubuntu
  
  tasks:
    - name: set timezone
      timezone: name=Asia/Tokyo

    - name: install other packages
      apt: name="{{ packages }}" state=latest
      vars:
        packages:
        - apt-transport-https
        - git
        - curl
        - software-properties-common

    # Add User

    # Setup kind
    # https://kind.sigs.k8s.io/
    - name: Download go 
      get_url:
        url: https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz
        dest: /tmp/go.tar.gz

    - name: Install go 
      unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local/bin
        remote_src: True

    - name: Install kind
      command: /usr/local/bin/go/bin/go get -u sigs.k8s.io/kind

    # Create Cluster
    # Set kind env in .bashrc
    # Output "kind get clusters"
    # Output "kubectl cluster-info"
